language: python
cache: pip

matrix:
  include:
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
    - python: '3.8'
      env: TOXENV=py38
    - python: 'pypy3'
      env: TOXENV=pypy3
    - env: TOXENV=flake8
    - env: TOXENV=checkspelling
      addons:
        apt:
          packages:
          - aspell
          - aspell-en
    - env: TOXENV=pep517check
    - env: TOXENV=checklinks
      before_install: npm install -g markdown-link-check

addons:
  apt:
    packages:
    - libtidy-0.99-0

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install codecov
  - codecov --flags "$TOXENV"

branches:
  only:
    - master
