site_name: Python-Markdown
site_url: https://Python-Markdown.github.io/
repo_url: https://github.com/Python-Markdown/markdown
site_author: "The Python-Markdown Project"
copyright: "Copyright &copy; 2010-2017"

use_directory_urls: true

theme:
  name: nature
  icon: py.png
  release: !!python/name:markdown.__version__
  issue_tracker: https://github.com/Python-Markdown/markdown/issues

nav:
  - Python-Markdown: index.md
  - Installation: install.md
  - Library Reference: reference.md
  - Command Line: cli.md
  - Extensions: extensions/index.md
  - Officially Supported Extensions:
      - Abbreviations: extensions/abbreviations.md
      - Admonition: extensions/admonition.md
      - Attribute Lists: extensions/attr_list.md
      - CodeHilite: extensions/code_hilite.md
      - Definition Lists: extensions/definition_lists.md
      - Extra: extensions/extra.md
      - Fenced Code Blocks: extensions/fenced_code_blocks.md
      - Footnotes: extensions/footnotes.md
      - Legacy Attributes: extensions/legacy_attr.md
      - Legacy Emphasis: extensions/legacy_em.md
      - Meta-Data: extensions/meta_data.md
      - New Line to Break: extensions/nl2br.md
      - Sane Lists: extensions/sane_lists.md
      - SmartyPants: extensions/smarty.md
      - Table of Contents: extensions/toc.md
      - Tables: extensions/tables.md
      - WikiLinks: extensions/wikilinks.md
  - Extension API: extensions/api.md
  - Test Tools: test_tools.md
  - Contributing to Python-Markdown: contributing.md
  - Change Log: change_log/index.md
  - Release Notes for v.3.1: change_log/release-3.1.md
  - Release Notes for v.3.0: change_log/release-3.0.md
  - Release Notes for v.2.6: change_log/release-2.6.md
  - Release Notes for v.2.5: change_log/release-2.5.md
  - Release Notes for v.2.4: change_log/release-2.4.md
  - Release Notes for v.2.3: change_log/release-2.3.md
  - Release Notes for v.2.2: change_log/release-2.2.md
  - Release Notes for v.2.1: change_log/release-2.1.md
  - Release Notes for v.2.0: change_log/release-2.0.md
  - Authors: authors.md

markdown_extensions:
  - extra
  - admonition
  - smarty
  - codehilite
  - toc:
      permalink: true
